### ISSUE TITLE
test not working

### ISSUE THREAD

**Issue by tomazbracic** [angelmz/learn-elixir-with-tests#2]
Hi, 

after you introduce the first test file, you kind of give misleading instructions on how to test. At least I can't test it as you suggested. 
You suggest running `elixir test` which won't do anything. 

Running for instance `elixir -r hello.ex hello_test.exs` will run the test normally.

**Comment by angelmz** [comment]
Hi tomas, 

My apologies. I left that incomplete. It should be: 
1. Run `elixirc hello.ex` to first compile the app.
2. Then, run `elixir hello_test.exs` 

Fixing that now.
